controller_list:
  - name: robot
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
